repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: fix-byte-order-marker

  # - repo: https://github.com/PyCQA/isort
  #   rev: 9.0.1
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/psf/black
  #   rev: 26.5.1
  #   hooks:
  #     - id: black
  #       language_version: python3
  #       args: ["--target-version", "py314"]

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 7.3.0
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        args: [--python-version=3.14]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
      - id: ruff-format

exclude: 'build/.*|.venv*/.*'
