channels:
- default
- conda-forge
dependencies:
- python>=3.8
- pip

# docs dependencies
- sphinx
- sphinx-autodoc-typehints
- pygments
- recommonmark

# testing dependencies
- pytest
- pytest-xdist
- pytest-pylint
- mypy>=0.8
- pytest-mypy
- pytest-cov

- pip:
  - docopt-ng
  - GitPython
  #- types-Jinja2

# testing dependencies
  - pytest-pycodestyle
  - pytest-pydocstyle

# install deploy in editable mode
#  - -e .
