name: RunTests
on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    # Service containers to run with `integration-tests`
    services:
      # Label used to access the service container
      nestserver:
        # Docker Hub image
        image: nest/nest-simulator:3.10
        env:
          NEST_CONTAINER_MODE: nest-server
          NEST_SERVER_STDOUT: 1
        ports:
          - 52425:52425
        # options: >-
        #   --health-cmd "curl http://localhost:52425"
        #   --health-interval 5s
        #   --health-timeout 3s
        #   --health-retries 5

    steps:
      # - uses: actions/checkout@v7

      # - name: Install uv
      #   uses: astral-sh/setup-uv@v10.0.1
      #   with:
      #     enable-cache: true

      # - name: Install the project
      #   run: uv sync --all-extras --dev

      # - run: uv run pytest

      - run: env
      - run: curl http://localhost:52425
      - run: >
          echo '{"mpi":false,"nest":"3.10.0"}' >expected;
          curl -s http://localhost:52425 | diff -u expected -
    env:
      server_version: "3.10"

  style-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --dev

      - run: uv run ruff check .
      - run: uv run ruff format --check .

      # - run: uv run pre-commit run --all-files
